import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import { SidebarNav } from "@/components/sidebar-nav";
import { TooltipProvider } from "@/components/ui/tooltip";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen flex flex-col overflow-hidden">
        <SessionProvider>
          <TooltipProvider>
            <div className="flex h-full min-h-0 flex-1 overflow-hidden bg-white">
              <SidebarNav />
              <main className="flex min-h-0 w-full flex-1 flex-col gap-4 overflow-y-auto px-8 py-6">
                {children}
              </main>
            </div>
          </TooltipProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
